### ISSUE TITLE
Some ethno- tags do not show up in the dropdown

### ISSUE THREAD

**Issue by aerugo** [edgeryders/graphryder#24]
Tag [ethno-icqe2022](https://edgeryders.eu/tag/ethno-icqe2022) does not show up in the dropdown on the landing page but it has data attached to it.

<img width="645" alt="Screenshot 2022-05-02 at 19 36 47" src="https://user-images.githubusercontent.com/7785081/166296711-8caf1e7b-252e-49bc-b6de-c5622dec97a3.png">

**Comment by tanius** [comment]
Solved as of today. Now, the dropdown of our Graphryder 2 installation at [graphryder.edgeryders.eu](http://graphryder.edgeryders.eu/) contains project `ethno-icqe2022`, and choosing it lets the user explore the data attached to it.

This was probably fixed by the transition from tags to projects in Open Ethnographer, which required corresponding changes to Graphryder.
